# Generated by Django 4.2.7 on 2023-11-23 07:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0002_artist_playlist_alter_score_options_song_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistitem',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
