# Generated by Django 4.2.7 on 2023-11-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0003_playlistitem_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(to='score.song'),
        ),
    ]
